import { ItrStep, ItrSummarySection } from "./itr-6.types";

export const ITR_SIX_PROGRESS_STEPS: ItrStep[] = [
	{ id: 1, title: "Company Information", caption: "Company Details & Registration" },
	{ id: 2, title: "Balance Sheet", caption: "Assets & Liabilities" },
	{ id: 3, title: "Manufacturing Account", caption: "Manufacturing & Production Details" },
	{ id: 4, title: "Trading Account", caption: "Trading & Commercial Details" },
	{ id: 5, title: "Other Information", caption: "Additional Details" },
	{ id: 6, title: "Schedule HP", caption: "House Property Income" },
	{ id: 7, title: "Schedule BP", caption: "Business/Profession Income" },
	{ id: 8, title: "Schedule DPM", caption: "Depreciation - Plant & Machinery" },
	{ id: 9, title: "Schedule DOA", caption: "Depreciation - Other Assets" },
	{ id: 10, title: "Schedule DEP", caption: "Depreciation Summary" },
	{ id: 11, title: "Schedule DCG", caption: "Details of Capital Gains" },
	{ id: 12, title: "Schedule ESR", caption: "Expenditure on Scientific Research" },
	{ id: 13, title: "Schedule CG", caption: "Capital Gains Computation" },
	{ id: 14, title: "Schedule 112A", caption: "Equity Share Transactions" },
	{ id: 15, title: "Schedule 115AD", caption: "Non-Residents - Equity Share Transactions" },
	{ id: 16, title: "Schedule VDA", caption: "Virtual Digital Assets" },
	{ id: 17, title: "Schedule OS", caption: "Income from Other Sources" },
	{ id: 18, title: "Schedule CYL", caption: "Income after Set off of Losses" },
	{ id: 19, title: "Schedule FI", caption: "Financial Information" },
	{ id: 20, title: "Schedule LSF", caption: "Losses to be Carried Forward" },
	{ id: 21, title: "Schedule UFD", caption: "Unabsorbed Depreciation & Allowance" },
	{ id: 22, title: "Schedule ICDS", caption: "Income Computation Disclosure Standards" },
	{ id: 23, title: "Schedule 16AA", caption: "SEZ Undertaking Deduction" },
	{ id: 24, title: "Schedule 80G", caption: "Charitable Donations Deduction" },
	{ id: 25, title: "Schedule 80GGA", caption: "Scientific Research Donations" },
	{ id: 26, title: "Schedule 80GGC", caption: "Political Contributions" },
	{ id: 27, title: "Schedule 81AC", caption: "Startup Investment Deduction" },
	{ id: 28, title: "Schedule 81LA", caption: "OBU/IFSC Deduction" },
	{ id: 29, title: "Schedule 80-IA", caption: "Industrial Undertaking Deduction" },
	{ id: 30, title: "Schedule 80-IB", caption: "Infrastructure & J&K/Ladakh" },
	{ id: 31, title: "Schedule 80-RA", caption: "Research Association Donations" },
	{ id: 32, title: "Schedule 80-IE", caption: "Green Technology Deduction" },
	{ id: 33, title: "Schedule 80-P", caption: "Cooperative Society Deduction" },
	{ id: 34, title: "Schedule VI-A", caption: "Summary of Chapter VI-A Deductions" },
	{ id: 35, title: "Schedule AMT", caption: "Alternate Minimum Tax Computation" },
	{ id: 36, title: "Schedule AMT Credit", caption: "AMT Credit Computation & Utilization" },
	{ id: 37, title: "Schedule SI", caption: "Special Income at Special Rates" },
	{ id: 38, title: "Schedule IF", caption: "Partnership Firm Information" },
	{ id: 39, title: "Schedule EX", caption: "Exempt Income Details" },
	{ id: 40, title: "Schedule PT", caption: "Pass Through Income Details" },
	{ id: 41, title: "Schedule TPSA", caption: "Tax on Secondary Adjustments" },
	{ id: 42, title: "Schedule 115TD", caption: "Accrued Income Computation" },
	{ id: 43, title: "Schedule FSI", caption: "Foreign Source Income" },
	{ id: 44, title: "Schedule TR", caption: "Tax Relief Summary" },
	{ id: 45, title: "Schedule FA", caption: "Foreign Assets Details" },
	{ id: 46, title: "Schedule GST", caption: "GST Turnover Information" },
	{ id: 47, title: "Schedule TI", caption: "Total Income Computation" },
	{ id: 48, title: "Schedule TTI", caption: "Tax Liability Computation" },
	{ id: 49, title: "Schedule TP", caption: "Tax Payments" },
	{ id: 50, title: "Schedule TDS", caption: "TDS and TCS Details" },
	{ id: 51, title: "Tax Computation", caption: "Tax Calculation & Payment" },
	{ id: 52, title: "Shareholding Pattern", caption: "Directors & Shareholders" },
];

export const ITR_SIX_SUMMARY_SECTIONS: ItrSummarySection[] = [
	{
		id: "company-info",
		title: "Company Information",
		description: "Includes company name, PAN, CIN, registration details, and registered office address",
		statusText: "Provide your confirmation",
		status: "in-progress",
	},
	{
		id: "balance-sheet",
		title: "Balance Sheet",
		description: "Balance sheet as on 31st day of March, 2025 - Sources and Application of Funds",
		statusText: "Provide balance sheet details",
		status: "pending",
	},
	{
		id: "manufacturing-account",
		title: "Manufacturing Account",
		description: "Manufacturing account for the financial year 2024-25 - Opening inventory, purchases, direct wages, and expenses",
		statusText: "Provide manufacturing account details",
		status: "pending",
	},
	{
		id: "trading-account",
		title: "Trading Account",
		description: "Trading account for the financial year 2024-25 - Opening inventory, purchases, sales, and trading expenses",
		statusText: "Provide trading account details",
		status: "pending",
	},
	{
		id: "other-info",
		title: "Other Information",
		description: "Other income sources, deductions, and relevant information",
		statusText: "Provide other information details",
		status: "pending",
	},
	{
		id: "schedule-hp",
		title: "Schedule HP",
		description: "House Property - Income from house property",
		statusText: "Provide house property details",
		status: "pending",
	},
	{
		id: "schedule-bp",
		title: "Schedule BP",
		description: "Business/Profession - Gross receipts, expenses, and profit computation",
		statusText: "Provide business/profession details",
		status: "pending",
	},
	{
		id: "schedule-dpm",
		title: "Schedule DPM",
		description: "Depreciation - Plant & Machinery with block-wise details",
		statusText: "Provide depreciation details for P&M",
		status: "pending",
	},
	{
		id: "schedule-doa",
		title: "Schedule DOA",
		description: "Depreciation - Other Assets with block-wise details",
		statusText: "Provide depreciation details for other assets",
		status: "pending",
	},
	{
		id: "schedule-dep",
		title: "Schedule DEP",
		description: "Depreciation Summary - Aggregate depreciation details",
		statusText: "Provide depreciation summary",
		status: "pending",
	},
	{
		id: "schedule-dcg",
		title: "Schedule DCG",
		description: "Details of Capital Gains - Asset-wise capital gains summary",
		statusText: "Provide capital gains details",
		status: "pending",
	},
	{
		id: "schedule-esr",
		title: "Schedule ESR",
		description: "Expenditure on Scientific Research - Eligible research expenses",
		statusText: "Provide scientific research expenditure",
		status: "pending",
	},
	{
		id: "schedule-cg",
		title: "Schedule CG",
		description: "Capital Gains Computation - Short-term and long-term capital gains",
		statusText: "Provide capital gains computation",
		status: "pending",
	},
	{
		id: "schedule-112a",
		title: "Schedule 112A",
		description: "Equity Share Transactions - Sale of equity shares in company or unit of equity oriented fund/business trust with STT",
		statusText: "Provide equity share transaction details",
		status: "pending",
	},
	{
		id: "schedule-115ad",
		title: "Schedule 115AD(10)(iii)",
		description: "Non-Residents - Sale of equity shares with STT paid",
		statusText: "Provide non-resident equity share details",
		status: "pending",
	},
	{
		id: "schedule-vda",
		title: "Schedule VDA",
		description: "Virtual Digital Assets - Income from transfer of virtual digital assets",
		statusText: "Provide virtual digital asset details",
		status: "pending",
	},
	{
		id: "schedule-os",
		title: "Schedule OS",
		description: "Income from Other Sources - Dividends, Interest, Rental Income, and Other Income",
		statusText: "Provide other sources income details",
		status: "pending",
	},
	{
		id: "schedule-cyl",
		title: "Schedule CYL",
		description: "Income after Set off of Losses - Computation of taxable income after loss adjustments and set-offs",
		statusText: "Provide income computation after loss set-off",
		status: "pending",
	},
	{
		id: "schedule-fi",
		title: "Schedule FI",
		description: "Financial Information - Revenue, Expenses, Balance Sheet, Financial Ratios and Quarterly Breakdown",
		statusText: "Provide financial information details",
		status: "pending",
	},
	{
		id: "schedule-lsf",
		title: "Schedule LSF",
		description: "Details of Losses to be Carried Forward to Future Years - Business, Capital, House Property, and Depreciation Losses",
		statusText: "Provide loss carry forward details",
		status: "pending",
	},
	{
		id: "schedule-ufd",
		title: "Schedule UFD",
		description: "Unabsorbed Depreciation and Allowance - Tracking depreciation and allowances carried forward across years",
		statusText: "Provide unabsorbed depreciation details",
		status: "pending",
	},
	{
		id: "schedule-icds",
		title: "Schedule ICDS",
		description: "Effect of Income Computation Disclosure Standards on Profit - Adjustments for accounting policy changes",
		statusText: "Provide ICDS adjustment details",
		status: "pending",
	},
	{
		id: "schedule-16aa",
		title: "Schedule 16AA",
		description: "Deduction under section 16AA for Units in SEZ - Special Economic Zone undertaking deductions",
		statusText: "Provide SEZ deduction details",
		status: "pending",
	},
	{
		id: "schedule-80g",
		title: "Schedule 80G",
		description: "Details of Donations - Charitable donations eligible for deduction under section 80G",
		statusText: "Provide donation details",
		status: "pending",
	},
	{
		id: "schedule-80gga",
		title: "Schedule 80GGA",
		description: "Donations for Scientific Research or Rural Development - Eligible donations for deduction",
		statusText: "Provide scientific research donation details",
		status: "pending",
	},
	{
		id: "schedule-80ggc",
		title: "Schedule 80GGC",
		description: "Political Contributions - Contributions made to political parties for deduction",
		statusText: "Provide political contribution details",
		status: "pending",
	},
	{
		id: "schedule-81ac",
		title: "Schedule 81AC",
		description: "Startup Investment Deduction - Investments in eligible startups as per DSIR/DPIIT certification",
		statusText: "Provide startup investment details",
		status: "pending",
	},
	{
		id: "schedule-81la",
		title: "Schedule 81LA",
		description: "OBU/IFSC Deduction - Deductions for Offshore Banking Units or IFSC units",
		statusText: "Provide OBU/IFSC details",
		status: "pending",
	},
	{
		id: "schedule-80ia",
		title: "Schedule 80-IA",
		description: "Industrial Undertaking Deduction - Deductions in respect of profits of an industrial undertaking",
		statusText: "Provide industrial undertaking details",
		status: "pending",
	},
	{
		id: "schedule-80ib",
		title: "Schedule 80-IB",
		description: "Infrastructure & J&K/Ladakh Deduction - Deductions for infrastructure undertakings and enterprises in J&K/Ladakh",
		statusText: "Provide infrastructure undertaking details",
		status: "pending",
	},
	{
		id: "schedule-80ra",
		title: "Schedule 80-RA",
		description: "Research Association Donations - Contributions to research associations and IPD schemes",
		statusText: "Provide research association contribution details",
		status: "pending",
	},
	{
		id: "schedule-80ie",
		title: "Schedule 80-IE",
		description: "Green Technology Deduction - Renewable energy, energy efficiency and environmental protection undertakings",
		statusText: "Provide green technology undertaking details",
		status: "pending",
	},
	{
		id: "schedule-80p",
		title: "Schedule 80-P",
		description: "Cooperative Society Deduction - Income from cooperative societies engaged in various business activities",
		statusText: "Provide cooperative society income details",
		status: "pending",
	},
	{
		id: "schedule-via",
		title: "Schedule VI-A",
		description: "Summary of Deductions under Chapter VI-A - Consolidated summary of all deductions under Chapter VI-A",
		statusText: "Provide summary of Chapter VI-A deductions",
		status: "pending",
	},
	{
		id: "schedule-amt",
		title: "Schedule AMT",
		description: "Alternate Minimum Tax (AMT) Computation - Computation of AMT payable under Section 115JC",
		statusText: "Provide AMT computation details",
		status: "pending",
	},
	{
		id: "schedule-amt-credit",
		title: "Schedule AMT Credit",
		description: "AMT Credit Computation under Section 115JD - Carry forward and utilization of AMT credit",
		statusText: "Provide AMT credit details",
		status: "pending",
	},
	{
		id: "schedule-si",
		title: "Schedule SI",
		description: "Special Income Taxed at Special Rates - Income chargeable at special rates under various sections",
		statusText: "Provide special income details",
		status: "pending",
	},
	{
		id: "schedule-if",
		title: "Schedule IF",
		description: "Partnership Firm Details - Information regarding partnership firms in which you are a partner",
		statusText: "Provide partnership firm details",
		status: "pending",
	},
	{
		id: "schedule-ex",
		title: "Schedule EX",
		description: "Exempt Income Details - Income not to be included in Total Income or not chargeable to tax",
		statusText: "Provide exempt income details",
		status: "pending",
	},
	{
		id: "schedule-pt",
		title: "Schedule PT",
		description: "Pass Through Income - Pass through income from business trust or investment fund as per Section 115U, 115UA and 115UB",
		statusText: "Provide pass through income details",
		status: "pending",
	},
	{
		id: "schedule-tpsa",
		title: "Schedule TPSA",
		description: "Tax on Secondary Adjustments - Details of tax on secondary adjustments as per Section 92CE(2A)",
		statusText: "Provide secondary adjustment details",
		status: "pending",
	},
	{
		id: "schedule-115td",
		title: "Schedule 115TD",
		description: "Accrued Income Computation - Complete accrued income computation under section 115TD for specified persons",
		statusText: "Provide accrued income details",
		status: "pending",
	},
	{
		id: "schedule-fsi",
		title: "Schedule FSI",
		description: "Foreign Source Income - Details of income from outside India and tax relief (available only in case of resident)",
		statusText: "Provide foreign source income details",
		status: "pending",
	},
	{
		id: "schedule-tr",
		title: "Schedule TR",
		description: "Tax Relief Summary - Details summary of tax relief claimed for taxes paid outside India (available only in case of resident)",
		statusText: "Provide tax relief summary details",
		status: "pending",
	},
	{
		id: "schedule-fa",
		title: "Schedule FA",
		description: "Foreign Assets Details - Comprehensive details of foreign deposits, financial interests, equity, insurance, property, and other assets held outside India",
		statusText: "Provide foreign assets details",
		status: "pending",
	},
	{
		id: "schedule-gst",
		title: "Schedule GST",
		description: "GST Turnover Information - Information regarding turnover/gross receipt reported for GST purposes with annual values from GST returns",
		statusText: "Provide GST turnover information",
		status: "pending",
	},
	{
		id: "schedule-ti",
		title: "Schedule TI",
		description: "Total Income Computation - Comprehensive computation of total income from all sources including house property, business, capital gains, and other sources with all applicable deductions",
		statusText: "Provide total income computation details",
		status: "pending",
	},
	{
		id: "schedule-tti",
		title: "Schedule TTI",
		description: "Tax Liability on Total Income - Complete tax computation including surcharge, health & education cess, rebates, tax relief, and bank account details for refund",
		statusText: "Provide tax liability computation details",
		status: "pending",
	},
	{
		id: "schedule-tp",
		title: "Schedule TP",
		description: "Tax Payments - Details of payments of Advance Tax and Self Assessment Tax with BSR codes, deposit dates, and challan serial numbers",
		statusText: "Provide tax payment details",
		status: "pending",
	},
	{
		id: "schedule-tds",
		title: "Schedule TDS",
		description: "TDS and TCS Details - Tax Deducted at Source (TDS) on income from various deductors and Tax Collected at Source (TCS) details with collector information",
		statusText: "Provide TDS/TCS details",
		status: "pending",
	},
];
