import { z } from "zod";

// PAN validation regex
const PAN_REGEX = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;

// Date validation helper (DD/MM/YYYY)
const DATE_REGEX = /^(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[0-2])\/\d{4}$/;

// PIN Code validation
const PIN_CODE_REGEX = /^\d{6}$/;

// CIN validation (21 characters)
const CIN_REGEX = /^[A-Z]{1}\d{5}[A-Z]{2}\d{4}[A-Z]{3}\d{6}$/;

// Email validation
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const itr7ValidationSchema = z.object({
  // Basic Company Information
  gen_name: z.string().min(3, "Company name must be at least 3 characters").optional(),
  gen_pan: z.string().regex(PAN_REGEX, "Invalid PAN format (e.g., ABCDE1234F)").optional(),
  gen_cin: z.string().regex(CIN_REGEX, "Invalid CIN format").optional().or(z.literal("")),
  
  // Name Change
  gen_name_change: z.string().optional(),
  gen_old_name: z.string().optional(),
  
  // Address Details
  gen_flat_door_block: z.string().optional(),
  gen_premises_building: z.string().optional(),
  gen_road_street_post: z.string().optional(),
  gen_area_locality: z.string().optional(),
  gen_town_city_district: z.string().optional(),
  gen_state: z.string().optional(),
  gen_pin_code: z.string().regex(PIN_CODE_REGEX, "Invalid PIN code (must be 6 digits)").optional().or(z.literal("")),
  gen_country: z.string().optional(),
  
  // Date validations
  gen_incorporation_date: z.string().regex(DATE_REGEX, "Date must be in DD/MM/YYYY format").optional().or(z.literal("")),
  gen_business_commencement_date: z.string().regex(DATE_REGEX, "Date must be in DD/MM/YYYY format").optional().or(z.literal("")),
  gen_filing_date: z.string().regex(DATE_REGEX, "Date must be in DD/MM/YYYY format").optional().or(z.literal("")),
  gen_due_date: z.string().optional(),
  
  // Contact Information
  gen_office_phone_std: z.string().regex(/^\d*$/, "STD code must contain only digits").optional().or(z.literal("")),
  gen_office_phone_mobile: z.string().regex(/^\d{10}$/, "Mobile number must be 10 digits").optional().or(z.literal("")),
  gen_mobile_2: z.string().regex(/^\d{10}$/, "Mobile number must be 10 digits").optional().or(z.literal("")),
  gen_email_1: z.string().regex(EMAIL_REGEX, "Invalid email format").optional().or(z.literal("")),
  gen_email_2: z.string().regex(EMAIL_REGEX, "Invalid email format").optional().or(z.literal("")),
  
  // Company Type
  gen_company_type: z.enum(["domestic", "foreign"]).optional(),
  gen_domestic_company_checkbox: z.boolean().optional(),
  gen_foreign_company_checkbox: z.boolean().optional(),
  gen_public_company_write_6: z.string().optional(),
  gen_private_company_write_7: z.string().optional(),
  
  // Filing Status
  gen_filed_us: z.string().optional(),
  gen_139_1_checkbox: z.boolean().optional(),
  gen_139_4_checkbox: z.boolean().optional(),
  gen_139_5_checkbox: z.boolean().optional(),
  gen_92cd_checkbox: z.boolean().optional(),
  gen_119_2b_checkbox: z.boolean().optional(),
  gen_92e_checkbox: z.boolean().optional(),
  
  // Return Type
  gen_original_return: z.boolean().optional(),
  gen_revised_return: z.boolean().optional(),
  gen_defective_modified: z.boolean().optional(),
  gen_receipt_number: z.string().optional(),
  gen_acknowledgement_number: z.string().optional(),
  
  // Response to Notice
  gen_response_to_notice: z.string().optional(),
  gen_unique_number: z.string().optional(),
  
  // Residential Status
  gen_residential_status: z.enum(["resident", "non-resident"]).optional(),
  
  // Taxation Sections
  gen_taxation_under_115ba: z.string().optional(),
  gen_taxation_option_exercised: z.string().optional(),
  gen_relevant_form_date: z.string().optional(),
  gen_acknowledgement_num: z.string().optional(),
  
  // Yes/No validations for various fields
  gen_total_turnover_exceeds_400cr: z.enum(["yes", "no"]).optional(),
  gen_country_agreement_90: z.enum(["yes", "no"]).optional(),
  gen_country_agreement_90a: z.enum(["yes", "no"]).optional(),
  gen_permanent_establishment: z.enum(["yes", "no"]).optional(),
  gen_significant_economic_presence: z.enum(["yes", "no"]).optional(),
  gen_transaction_provisions: z.enum(["yes", "no"]).optional(),
  gen_cross_reference: z.enum(["yes", "no"]).optional(),
  gen_registration_under_law: z.enum(["yes", "no"]).optional(),
  gen_financial_statements_compliance: z.enum(["yes", "no"]).optional(),
  gen_ifsc_unit: z.enum(["yes", "no"]).optional(),
  gen_foreign_exchange: z.enum(["yes", "no"]).optional(),
  gen_under_liquidation: z.enum(["yes", "no"]).optional(),
  gen_fii_fpi: z.enum(["yes", "no"]).optional(),
  gen_producer_company: z.enum(["yes", "no"]).optional(),
  gen_representative_assessee: z.enum(["yes", "no"]).optional(),
  gen_startup_recognition: z.enum(["yes", "no"]).optional(),
  gen_msme_recognition: z.enum(["yes", "no"]).optional(),
  gen_maintain_accounts_44aa: z.enum(["yes", "no"]).optional(),
  gen_income_declaration_44bb: z.enum(["yes", "no"]).optional(),
  gen_sales_exceeds_1cr: z.enum(["yes", "no"]).optional(),
  gen_aggregate_payments: z.enum(["yes", "no"]).optional(),
  gen_audit_liable_44ab: z.enum(["yes", "no"]).optional(),
  gen_audit_accounts_audited: z.enum(["yes", "no"]).optional(),
  gen_audit_liable_92e: z.enum(["yes", "no"]).optional(),
  
  // Additional fields
  gen_transaction_explanation: z.string().optional(),
  gen_cross_reference_explanation: z.string().optional(),
  gen_registration_details: z.string().optional(),
  gen_registration_date: z.string().optional(),
  gen_registration_number: z.string().optional(),
  gen_sebi_registration: z.string().optional(),
  gen_representative_name: z.string().optional(),
  gen_representative_capacity: z.string().optional(),
  gen_representative_address: z.string().optional(),
  gen_representative_pan_aadhaar: z.string().optional(),
  gen_dpiit_startup_number: z.string().optional(),
  gen_inter_ministerial_certificate: z.string().optional(),
  gen_certificate_number: z.string().optional(),
  gen_dpiit_para5_declaration: z.string().optional(),
  gen_form2_filing_date: z.string().optional(),
  gen_lei_number: z.string().optional(),
  gen_lei_valid_date: z.string().optional(),
  gen_msme_registration: z.string().optional(),
  gen_sales_exceeds_option: z.string().optional(),
  gen_building_amount: z.string().optional(),
  gen_cash_bank_amount: z.string().optional(),
  gen_aggregate_cash_bank: z.string().optional(),
  gen_audit_condition: z.string().optional(),
  gen_audit_report_date: z.string().optional(),
  gen_auditor_name: z.string().optional(),
  gen_auditor_membership: z.string().optional(),
  gen_auditor_firm_name: z.string().optional(),
  gen_auditor_registration: z.string().optional(),
  gen_auditor_pan: z.string().optional(),
  gen_audit_date: z.string().optional(),
  gen_audit_acknowledgement: z.string().optional(),
  gen_udin: z.string().optional(),
  gen_accounts_audited_92e: z.string().optional(),
  gen_furnishing_date_92e: z.string().optional(),
  gen_acknowledgement_92e: z.string().optional(),
  gen_other_audit_report: z.string().optional(),
  gen_other_audit_details: z.string().optional(),
  gen_other_act: z.string().optional(),
  gen_other_section: z.string().optional(),
  gen_other_furnishing_date: z.string().optional(),

  // Balance Sheet - Share Capital (Part A-BS Section I.1.A)
  bs_share_capital_authorised: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_capital_issued: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_capital_subscribed: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Reserves and Surplus (Part A-BS Section I.1.B)
  bs_capital_reserve: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_capital_redemption_reserve: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_securities_premium_reserve: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_debenture_redemption_reserve: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_revaluation_reserve: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_options_outstanding: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_reserve_a: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_reserve_b: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_surplus_profit_loss: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Share Application Money (Part A-BS Section I.2)
  bs_share_application_pending_1yr: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_application_pending_over1yr: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_application_less_1year: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_share_application_more_1year: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Non-current Liabilities (Part A-BS Section I.3)
  bs_bonds_foreign_currency: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_bonds_rupees: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_term_loans_banks: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_term_loans_others: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_deferred_payment_liabilities: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_deposits_related_parties: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_deposits: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_loans_advances_related: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_loans_advances: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_finance_lease_obligations: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Current Liabilities (Part A-BS Section I.4)
  bs_current_liabilities_borrowings: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_current_liabilities_trade_payables: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_current_liabilities_other_payables: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Non-current Assets (Part A-BS Section II.1)
  bs_fixed_assets_gross: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_fixed_assets_gross_block: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_fixed_assets_depreciation: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_goodwill_intangibles: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_noncurrent_assets: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Balance Sheet - Current Assets (Part A-BS Section II.2)
  bs_inventories: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_trade_receivables: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_cash_equivalents: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  bs_other_current_assets: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),
  
  // Balance Sheet - Surplus field
  bs_surplus_balance: z.string().regex(/^\d+(\.\d{1,2})?$/, "Must be a valid number").optional().or(z.literal("")),

  // Part A-TS: Trading Statement
  // Section I: Cost of Materials Consumed
  ts_opening_stock: z.number().min(0, "Must be zero or positive").optional(),
  ts_purchases: z.number().min(0, "Must be zero or positive").optional(),
  ts_carriage_inbound: z.number().min(0, "Must be zero or positive").optional(),
  ts_purchase_returns: z.number().min(0, "Must be zero or positive").optional(),
  ts_import_duty: z.number().min(0, "Must be zero or positive").optional(),
  ts_octroi: z.number().min(0, "Must be zero or positive").optional(),
  ts_other_materials: z.number().min(0, "Must be zero or positive").optional(),
  ts_closing_stock: z.number().min(0, "Must be zero or positive").optional(),
  
  // Section II: Manufacturing Expenses (Direct Expenses)
  ts_labour: z.number().min(0, "Must be zero or positive").optional(),
  ts_power_fuel: z.number().min(0, "Must be zero or positive").optional(),
  ts_freight_cartage: z.number().min(0, "Must be zero or positive").optional(),
  ts_manufacturing_overheads: z.number().min(0, "Must be zero or positive").optional(),
  ts_other_direct_expenses: z.number().min(0, "Must be zero or positive").optional(),
  ts_other_manufacturing_expenses: z.number().min(0, "Must be zero or positive").optional(),
  
  // Section III: Work in Progress
  ts_opening_wip: z.number().min(0, "Must be zero or positive").optional(),
  ts_closing_wip: z.number().min(0, "Must be zero or positive").optional(),
  
  // Section IV: Semi-Finished Goods
  ts_opening_semifinished: z.number().min(0, "Must be zero or positive").optional(),
  ts_closing_semifinished: z.number().min(0, "Must be zero or positive").optional(),
  
  // Section V: Cost of Goods Sold
  ts_opening_finished_goods: z.number().min(0, "Must be zero or positive").optional(),
  ts_closing_finished_goods: z.number().min(0, "Must be zero or positive").optional(),
  
  // Section VI: Revenue from Operations
  ts_sales: z.number().min(0, "Must be zero or positive").optional(),
  ts_sales_returns: z.number().min(0, "Must be zero or positive").optional(),
  ts_excise_duty: z.number().min(0, "Must be zero or positive").optional(),
  ts_trade_discount: z.number().min(0, "Must be zero or positive").optional(),
  ts_freight_outbound: z.number().min(0, "Must be zero or positive").optional(),
  ts_packaging: z.number().min(0, "Must be zero or positive").optional(),
  ts_other_revenue: z.number().min(0, "Must be zero or positive").optional(),
  
  // Part A-P&L: Profit & Loss Statement
  // Operating Expenses
  ts_employee_benefits: z.number().min(0, "Must be zero or positive").optional(),
  ts_finance_costs: z.number().min(0, "Must be zero or positive").optional(),
  ts_depreciation: z.number().min(0, "Must be zero or positive").optional(),
  ts_amortization: z.number().min(0, "Must be zero or positive").optional(),
  ts_research_development: z.number().min(0, "Must be zero or positive").optional(),
  ts_administrative_expenses: z.number().min(0, "Must be zero or positive").optional(),
  ts_selling_distribution: z.number().min(0, "Must be zero or positive").optional(),
  ts_other_operating_expenses: z.number().min(0, "Must be zero or positive").optional(),
  
  // Other Income & Items
  ts_other_income: z.number().min(0, "Must be zero or positive").optional(),
  ts_exceptional_items: z.number().min(0, "Must be zero or positive").optional(),
  ts_prior_period_adjustments: z.number().min(0, "Must be zero or positive").optional(),
  ts_tax_expense: z.number().min(0, "Must be zero or positive").optional(),

  // Part A-TS: Additional Asset Schedules
  // Current Assets - Inventories
  ts_inv_raw_materials: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_work_in_progress: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_finished_goods: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_stock_in_trade: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_stores_spares: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_loose_tools: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_other_inventory: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Financial Assets - Investments
  ts_inv_listed_equities: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_unlisted_equities: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_preference_shares: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_government_securities: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_debentures_bonds: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_mutual_funds: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_partnership_firms: z.number().min(0, "Must be zero or positive").optional(),
  ts_inv_other_investments: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Trade Receivables
  ts_tr_secured_good: z.number().min(0, "Must be zero or positive").optional(),
  ts_tr_unsecured_good: z.number().min(0, "Must be zero or positive").optional(),
  ts_tr_doubtful: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Cash & Cash Equivalents
  ts_cash_bank_balances: z.number().min(0, "Must be zero or positive").optional(),
  ts_cash_cheques_drafts: z.number().min(0, "Must be zero or positive").optional(),
  ts_cash_on_hand: z.number().min(0, "Must be zero or positive").optional(),
  ts_cash_others: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Bank Balances
  ts_bank_balances_other: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Loans
  ts_loans_security_deposits: z.number().min(0, "Must be zero or positive").optional(),
  ts_loans_related_parties: z.number().min(0, "Must be zero or positive").optional(),
  ts_loans_other: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Loans Included in V above
  ts_loans_business_profession: z.number().min(0, "Must be zero or positive").optional(),
  ts_loans_shareholder_benefit: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Other Financial Assets
  ts_financial_assets_other: z.number().min(0, "Must be zero or positive").optional(),

  // Current Assets - Others
  ts_current_assets_advances: z.number().min(0, "Must be zero or positive").optional(),
  ts_current_assets_other: z.number().min(0, "Must be zero or positive").optional(),

  // MANUFACTURING ACCOUNT FIELDS
  // A. Opening Inventory
  mfg_opening_raw_materials: z.number().min(0, "Must be zero or positive").optional(),
  mfg_opening_wip: z.number().min(0, "Must be zero or positive").optional(),

  // B. Purchases
  mfg_purchases: z.number().min(0, "Must be zero or positive").optional(),
  mfg_purchase_returns: z.number().min(0, "Must be zero or positive").optional(),
  mfg_carriage_inward: z.number().min(0, "Must be zero or positive").optional(),
  mfg_import_duty: z.number().min(0, "Must be zero or positive").optional(),
  mfg_octroi: z.number().min(0, "Must be zero or positive").optional(),
  mfg_other_materials_consumed: z.number().min(0, "Must be zero or positive").optional(),

  // C. Direct Wages
  mfg_direct_wages: z.number().min(0, "Must be zero or positive").optional(),

  // D. Direct Expenses
  mfg_direct_expenses_carriage: z.number().min(0, "Must be zero or positive").optional(),
  mfg_power_and_fuel: z.number().min(0, "Must be zero or positive").optional(),
  mfg_other_direct_expenses: z.number().min(0, "Must be zero or positive").optional(),

  // E. Factory Overheads
  mfg_indirect_wages: z.number().min(0, "Must be zero or positive").optional(),
  mfg_factory_rent_and_rates: z.number().min(0, "Must be zero or positive").optional(),
  mfg_factory_insurance: z.number().min(0, "Must be zero or positive").optional(),
  mfg_factory_fuel_and_power: z.number().min(0, "Must be zero or positive").optional(),
  mfg_factory_general_expenses: z.number().min(0, "Must be zero or positive").optional(),
  mfg_depreciation_factory_machinery: z.number().min(0, "Must be zero or positive").optional(),

  // Closing Stock
  mfg_closing_raw_materials: z.number().min(0, "Must be zero or positive").optional(),
  mfg_closing_wip: z.number().min(0, "Must be zero or positive").optional(),
  mfg_closing_finished_goods: z.number().min(0, "Must be zero or positive").optional(),

  // TRADING ACCOUNT FIELDS
  // Revenue from Operations
  trd_sale_of_goods: z.number().min(0, "Must be zero or positive").optional(),
  trd_sale_of_services: z.number().min(0, "Must be zero or positive").optional(),
  trd_other_operating_revenues_a: z.number().min(0, "Must be zero or positive").optional(),
  trd_other_operating_revenues_b: z.number().min(0, "Must be zero or positive").optional(),

  // Gross receipts from Profession
  trd_gross_receipts_profession: z.number().min(0, "Must be zero or positive").optional(),

  // Duties, taxes and cess
  trd_custom_duty: z.number().min(0, "Must be zero or positive").optional(),
  trd_counter_velling_duty: z.number().min(0, "Must be zero or positive").optional(),
  trd_services_tax: z.number().min(0, "Must be zero or positive").optional(),
  trd_vat_sales_tax: z.number().min(0, "Must be zero or positive").optional(),
  trd_cgst: z.number().min(0, "Must be zero or positive").optional(),
  trd_sgst: z.number().min(0, "Must be zero or positive").optional(),
  trd_igst: z.number().min(0, "Must be zero or positive").optional(),
  trd_utgst: z.number().min(0, "Must be zero or positive").optional(),

  // Cost of Goods Sold
  trd_closing_stock_finished_goods: z.number().min(0, "Must be zero or positive").optional(),
  trd_total_credits_trading_account: z.number().min(0, "Must be zero or positive").optional(),
  trd_opening_stock_finished_goods: z.number().min(0, "Must be zero or positive").optional(),
  trd_purchases_net_of_refunds: z.number().min(0, "Must be zero or positive").optional(),
  trd_carriage_inward_trading: z.number().min(0, "Must be zero or positive").optional(),
  trd_power_and_fuel_trading: z.number().min(0, "Must be zero or positive").optional(),
  trd_other_direct_expenses_trading: z.number().min(0, "Must be zero or positive").optional(),

  // PROFIT & LOSS ACCOUNT FIELDS
  // 13. Gross Profit
  pl_gross_profit: z.number().min(0, "Must be zero or positive").optional(),

  // 14. Other Income
  pl_rent: z.number().min(0, "Must be zero or positive").optional(),
  pl_commission: z.number().min(0, "Must be zero or positive").optional(),
  pl_dividend_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_interest_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_profit_sale_fixed_assets: z.number().min(0, "Must be zero or positive").optional(),
  pl_profit_securities_transaction: z.number().min(0, "Must be zero or positive").optional(),
  pl_profit_other_investment: z.number().min(0, "Must be zero or positive").optional(),
  pl_gain_foreign_exchange: z.number().min(0, "Must be zero or positive").optional(),
  pl_profit_inventory_conversion: z.number().min(0, "Must be zero or positive").optional(),
  pl_agricultural_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_income_a: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_income_b: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_income_c: z.number().min(0, "Must be zero or positive").optional(),

  // 15-46. Operating and Other Expenses
  pl_freight_outward: z.number().min(0, "Must be zero or positive").optional(),
  pl_consumption_stores: z.number().min(0, "Must be zero or positive").optional(),
  pl_power_fuel: z.number().min(0, "Must be zero or positive").optional(),
  pl_rents: z.number().min(0, "Must be zero or positive").optional(),
  pl_repairs_building: z.number().min(0, "Must be zero or positive").optional(),
  pl_repairs_machinery: z.number().min(0, "Must be zero or positive").optional(),
  pl_compensation_employees: z.number().min(0, "Must be zero or positive").optional(),

  // 22. Compensation to employees
  pl_salaries_wages: z.number().min(0, "Must be zero or positive").optional(),
  pl_bonus: z.number().min(0, "Must be zero or positive").optional(),
  pl_medical_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_leave_encashment: z.number().min(0, "Must be zero or positive").optional(),
  pl_leave_travel: z.number().min(0, "Must be zero or positive").optional(),
  pl_approved_welfare: z.number().min(0, "Must be zero or positive").optional(),
  pl_recognised_provident: z.number().min(0, "Must be zero or positive").optional(),
  pl_recognised_gratuity: z.number().min(0, "Must be zero or positive").optional(),
  pl_contribution_other_fund: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_benefit_employees: z.number().min(0, "Must be zero or positive").optional(),

  // 23. Insurance
  pl_medical_insurance: z.number().min(0, "Must be zero or positive").optional(),
  pl_life_insurance: z.number().min(0, "Must be zero or positive").optional(),
  pl_keyman_insurance: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_insurance: z.number().min(0, "Must be zero or positive").optional(),

  // 24-43
  pl_workmen_staff: z.number().min(0, "Must be zero or positive").optional(),
  pl_entertainment: z.number().min(0, "Must be zero or positive").optional(),
  pl_hospitality: z.number().min(0, "Must be zero or positive").optional(),
  pl_conference: z.number().min(0, "Must be zero or positive").optional(),
  pl_sales_promotion: z.number().min(0, "Must be zero or positive").optional(),
  pl_advertisement: z.number().min(0, "Must be zero or positive").optional(),

  // 30. Commission
  pl_commission_paid_i: z.number().min(0, "Must be zero or positive").optional(),
  pl_commission_paid_ii: z.number().min(0, "Must be zero or positive").optional(),

  // 31. Royalty
  pl_royalty_paid_i: z.number().min(0, "Must be zero or positive").optional(),
  pl_royalty_paid_ii: z.number().min(0, "Must be zero or positive").optional(),

  // 32. Professional Fees
  pl_professional_fees_i: z.number().min(0, "Must be zero or positive").optional(),
  pl_professional_fees_ii: z.number().min(0, "Must be zero or positive").optional(),

  // 33-43. Travel and other expenses
  pl_hotel_boarding: z.number().min(0, "Must be zero or positive").optional(),
  pl_travelling_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_foreign_travelling: z.number().min(0, "Must be zero or positive").optional(),
  pl_conveyance_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_telephone_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_guest_house_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_club_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_festival_celebration: z.number().min(0, "Must be zero or positive").optional(),
  pl_scholarship: z.number().min(0, "Must be zero or positive").optional(),
  pl_gift: z.number().min(0, "Must be zero or positive").optional(),
  pl_donation: z.number().min(0, "Must be zero or positive").optional(),

  // 44. Rates and taxes
  pl_union_excise_duty: z.number().min(0, "Must be zero or positive").optional(),
  pl_services_tax: z.number().min(0, "Must be zero or positive").optional(),
  pl_vat_sales_tax: z.number().min(0, "Must be zero or positive").optional(),
  pl_cgst: z.number().min(0, "Must be zero or positive").optional(),
  pl_sgst: z.number().min(0, "Must be zero or positive").optional(),
  pl_igst: z.number().min(0, "Must be zero or positive").optional(),
  pl_utgst: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_tax: z.number().min(0, "Must be zero or positive").optional(),

  // 45-46
  pl_audit_fee: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_expenses_i: z.number().min(0, "Must be zero or positive").optional(),
  pl_other_expenses_ii: z.number().min(0, "Must be zero or positive").optional(),

  // Updated Profit & Loss validations (Complete Form)
  pl_new_gross_profit: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_rent: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_commission: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_dividend_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_interest_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_profit_fixed_assets: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_profit_securities: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_profit_other_investment: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_foreign_exchange_gain: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_inventory_conversion: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_agricultural_income: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_income_a: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_income_b: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_income_c: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_freight_outward: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_consumption_stores: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_power_fuel: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_rents: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_repairs_building: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_repairs_machinery: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_compensation_employees: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_medical_insurance: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_workmen_welfare: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_entertainment: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_hospitality: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_conference: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_sales_promotion: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_advertisement: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_royalty: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_professional_fees: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_hotel_boarding: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_travelling_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_foreign_travelling: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_conveyance: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_telephone: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_guest_house: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_club_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_festival_celebration: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_scholarship: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_gift: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_donation: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_rates_taxes: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_audit_fee: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_expenses: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_bad_debts_over_1lakh: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_bad_debts_under_1lakh: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_provision_bad_debts: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_provisions: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_interest_outside: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_interest_others: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_depreciation_amortization: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_current_tax_provision: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_deferred_tax_provision: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_balance_previous_year: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_transfer_reserves: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_dividend: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_tax_dividend: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_csr_appropriation: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_other_appropriation: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_remeasurement_changes: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_equity_changes: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_exchange_differences: z.number().min(0, "Must be zero or positive").optional(),
  pl_new_hedging_gains: z.number().min(0, "Must be zero or positive").optional(),

  // Other Information validations
  oi_accounting_method_prev: z.string().optional(),
  oi_accounting_method_change: z.string().optional(),
  oi_accounting_change_details: z.string().optional(),
  oi_stock_valuation_method: z.string().optional(),
  oi_finished_goods_method: z.number().min(1).max(3).optional(),
  oi_stock_valuation_change: z.string().optional(),
  oi_profit_increase_icds: z.number().min(0, "Must be zero or positive").optional(),
  oi_profit_decrease_valuation: z.number().min(0, "Must be zero or positive").optional(),
  oi_closing_stock_valuation: z.string().optional(),
  oi_items_section_28: z.number().min(0, "Must be zero or positive").optional(),
  oi_proforma_credits: z.number().min(0, "Must be zero or positive").optional(),
  oi_escalation_claims: z.number().min(0, "Must be zero or positive").optional(),
  oi_other_income_item: z.number().min(0, "Must be zero or positive").optional(),
  oi_capital_receipt: z.number().min(0, "Must be zero or positive").optional(),
  oi_insurance_premium: z.number().min(0, "Must be zero or positive").optional(),
  oi_health_insurance_premium: z.number().min(0, "Must be zero or positive").optional(),
  oi_employee_bonus_commission: z.number().min(0, "Must be zero or positive").optional(),
  oi_interest_borrowed_capital: z.number().min(0, "Must be zero or positive").optional(),
  oi_provident_fund_contribution: z.number().min(0, "Must be zero or positive").optional(),
  oi_pension_contribution: z.number().min(0, "Must be zero or positive").optional(),
  oi_gratuity_fund_contribution: z.number().min(0, "Must be zero or positive").optional(),
  oi_other_fund_contribution: z.number().min(0, "Must be zero or positive").optional(),
  oi_bad_debts_allowance: z.number().min(0, "Must be zero or positive").optional(),
  oi_bad_debts_provision: z.number().min(0, "Must be zero or positive").optional(),
  oi_special_reserve_transfer: z.number().min(0, "Must be zero or positive").optional(),
  oi_family_planning_expenditure: z.number().min(0, "Must be zero or positive").optional(),
  oi_capital_expenditure_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_personal_expenditure_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_npl_expenditure_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_penalty_fine_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_offence_purpose_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_csr_expenditure_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_contingent_liability_disallow: z.number().min(0, "Must be zero or positive").optional(),
  oi_other_disallow: z.number().min(0, "Must be zero or positive").optional(),

  // Quantitative Details validations
  // Trading
  qd_trading_opening_stock: z.number().min(0, "Must be zero or positive").optional(),
  qd_trading_opening_stock_unit: z.string().optional(),
  qd_trading_purchase: z.number().min(0, "Must be zero or positive").optional(),
  qd_trading_purchase_unit: z.string().optional(),
  qd_trading_sales: z.number().min(0, "Must be zero or positive").optional(),
  qd_trading_sales_unit: z.string().optional(),
  qd_trading_closing_stock: z.number().min(0, "Must be zero or positive").optional(),
  qd_trading_closing_stock_unit: z.string().optional(),
  qd_trading_shortage_excess: z.number().min(0, "Must be zero or positive").optional(),
  qd_trading_shortage_excess_unit: z.string().optional(),

  // Manufacturing - Raw Materials
  qd_mfg_raw_opening: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_raw_opening_unit: z.string().optional(),
  qd_mfg_raw_purchase: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_raw_purchase_unit: z.string().optional(),
  qd_mfg_raw_consumption: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_raw_consumption_unit: z.string().optional(),
  qd_mfg_raw_closing: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_raw_closing_unit: z.string().optional(),
  qd_mfg_raw_shortage: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_raw_shortage_unit: z.string().optional(),

  // Manufacturing - Finished Products
  qd_mfg_fp_opening: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_fp_opening_unit: z.string().optional(),
  qd_mfg_fp_manufactured: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_fp_manufactured_unit: z.string().optional(),
  qd_mfg_fp_sales: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_fp_sales_unit: z.string().optional(),
  qd_mfg_fp_closing: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_fp_closing_unit: z.string().optional(),
  qd_mfg_fp_shortage: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_fp_shortage_unit: z.string().optional(),

  // Manufacturing - By-products
  qd_mfg_byp_opening: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_opening_unit: z.string().optional(),
  qd_mfg_byp_purchase: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_purchase_unit: z.string().optional(),
  qd_mfg_byp_manufactured: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_manufactured_unit: z.string().optional(),
  qd_mfg_byp_sales: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_sales_unit: z.string().optional(),
  qd_mfg_byp_closing: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_closing_unit: z.string().optional(),
  qd_mfg_byp_shortage: z.number().min(0, "Must be zero or positive").optional(),
  qd_mfg_byp_shortage_unit: z.string().optional(),

  // Receipt and Payment Account validations
  rpa_opening_cash: z.number().min(0, "Must be zero or positive").optional(),
  rpa_opening_bank: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_interest: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_dividend: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_sale_assets_a: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_sale_assets_b: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_sale_assets_c: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_sale_assets_total: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_realization_debtors: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_others_a: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_others_b: z.number().min(0, "Must be zero or positive").optional(),
  rpa_receipt_others_total: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_repayment_secured: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_repayment_unsecured: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_repayment_creditors: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_commission: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_others_a: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_others_b: z.number().min(0, "Must be zero or positive").optional(),
  rpa_payment_others_total: z.number().min(0, "Must be zero or positive").optional(),
  rpa_closing_cash: z.number().min(0, "Must be zero or positive").optional(),
  rpa_closing_bank: z.number().min(0, "Must be zero or positive").optional(),

  // House Property Schedule validations - Property 1
  hp_property_1_address: z.string().optional(),
  hp_property_1_city: z.string().optional(),
  hp_property_1_state: z.string().optional(),
  hp_property_1_country: z.string().optional(),
  hp_property_1_pincode: z.string().optional(),
  hp_property_1_coowned: z.string().optional(),
  hp_property_1_ownership_percentage: z.number().min(0).max(100).optional(),
  hp_property_1_coowner_1_name: z.string().optional(),
  hp_property_1_coowner_1_pan: z.string().optional(),
  hp_property_1_coowner_1_share: z.number().min(0).max(100).optional(),
  hp_property_1_coowner_2_name: z.string().optional(),
  hp_property_1_coowner_2_pan: z.string().optional(),
  hp_property_1_coowner_2_share: z.number().min(0).max(100).optional(),
  hp_property_1_gross_rent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_rent_not_realised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_tax_local_authorities: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_total_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_annual_value: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_annual_value_owned: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_thirty_percent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_interest_borrowed: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_arrears_unrealised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_1_income_property: z.number().optional(),
  hp_property_1_passthrough_loss: z.number().optional(),
  hp_property_1_total_income_property: z.number().optional(),

  // House Property Schedule validations - Property 2
  hp_property_2_address: z.string().optional(),
  hp_property_2_city: z.string().optional(),
  hp_property_2_state: z.string().optional(),
  hp_property_2_country: z.string().optional(),
  hp_property_2_pincode: z.string().optional(),
  hp_property_2_coowned: z.string().optional(),
  hp_property_2_ownership_percentage: z.number().min(0).max(100).optional(),
  hp_property_2_coowner_1_name: z.string().optional(),
  hp_property_2_coowner_1_pan: z.string().optional(),
  hp_property_2_coowner_1_share: z.number().min(0).max(100).optional(),
  hp_property_2_coowner_2_name: z.string().optional(),
  hp_property_2_coowner_2_pan: z.string().optional(),
  hp_property_2_coowner_2_share: z.number().min(0).max(100).optional(),
  hp_property_2_gross_rent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_rent_not_realised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_tax_local_authorities: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_total_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_annual_value: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_annual_value_owned: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_thirty_percent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_interest_borrowed: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_arrears_unrealised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_2_income_property: z.number().optional(),
  hp_property_2_passthrough_loss: z.number().optional(),
  hp_property_2_total_income_property: z.number().optional(),

  // House Property Schedule validations - Property 3
  hp_property_3_address: z.string().optional(),
  hp_property_3_city: z.string().optional(),
  hp_property_3_state: z.string().optional(),
  hp_property_3_country: z.string().optional(),
  hp_property_3_pincode: z.string().optional(),
  hp_property_3_coowned: z.string().optional(),
  hp_property_3_ownership_percentage: z.number().min(0).max(100).optional(),
  hp_property_3_coowner_1_name: z.string().optional(),
  hp_property_3_coowner_1_pan: z.string().optional(),
  hp_property_3_coowner_1_share: z.number().min(0).max(100).optional(),
  hp_property_3_coowner_2_name: z.string().optional(),
  hp_property_3_coowner_2_pan: z.string().optional(),
  hp_property_3_coowner_2_share: z.number().min(0).max(100).optional(),
  hp_property_3_gross_rent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_rent_not_realised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_tax_local_authorities: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_total_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_annual_value: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_annual_value_owned: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_thirty_percent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_interest_borrowed: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_arrears_unrealised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_3_income_property: z.number().optional(),
  hp_property_3_passthrough_loss: z.number().optional(),
  hp_property_3_total_income_property: z.number().optional(),

  // House Property Schedule validations - Property 4
  hp_property_4_address: z.string().optional(),
  hp_property_4_city: z.string().optional(),
  hp_property_4_state: z.string().optional(),
  hp_property_4_country: z.string().optional(),
  hp_property_4_pincode: z.string().optional(),
  hp_property_4_coowned: z.string().optional(),
  hp_property_4_ownership_percentage: z.number().min(0).max(100).optional(),
  hp_property_4_coowner_1_name: z.string().optional(),
  hp_property_4_coowner_1_pan: z.string().optional(),
  hp_property_4_coowner_1_share: z.number().min(0).max(100).optional(),
  hp_property_4_coowner_2_name: z.string().optional(),
  hp_property_4_coowner_2_pan: z.string().optional(),
  hp_property_4_coowner_2_share: z.number().min(0).max(100).optional(),
  hp_property_4_gross_rent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_rent_not_realised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_tax_local_authorities: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_total_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_annual_value: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_annual_value_owned: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_thirty_percent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_interest_borrowed: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_arrears_unrealised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_4_income_property: z.number().optional(),
  hp_property_4_passthrough_loss: z.number().optional(),
  hp_property_4_total_income_property: z.number().optional(),

  // House Property Schedule validations - Property 5
  hp_property_5_address: z.string().optional(),
  hp_property_5_city: z.string().optional(),
  hp_property_5_state: z.string().optional(),
  hp_property_5_country: z.string().optional(),
  hp_property_5_pincode: z.string().optional(),
  hp_property_5_coowned: z.string().optional(),
  hp_property_5_ownership_percentage: z.number().min(0).max(100).optional(),
  hp_property_5_coowner_1_name: z.string().optional(),
  hp_property_5_coowner_1_pan: z.string().optional(),
  hp_property_5_coowner_1_share: z.number().min(0).max(100).optional(),
  hp_property_5_coowner_2_name: z.string().optional(),
  hp_property_5_coowner_2_pan: z.string().optional(),
  hp_property_5_coowner_2_share: z.number().min(0).max(100).optional(),
  hp_property_5_gross_rent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_rent_not_realised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_tax_local_authorities: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_total_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_annual_value: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_annual_value_owned: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_thirty_percent: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_interest_borrowed: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_deduction: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_arrears_unrealised: z.number().min(0, "Must be zero or positive").optional(),
  hp_property_5_income_property: z.number().optional(),
  hp_property_5_passthrough_loss: z.number().optional(),
  hp_property_5_total_income_property: z.number().optional(),

  // Cash Flow Statement validations
  cf_net_profit_loss: z.number().min(0, "Must be zero or positive").optional(),
  cf_depreciation: z.number().min(0, "Must be zero or positive").optional(),
  cf_amortization: z.number().min(0, "Must be zero or positive").optional(),
  cf_impairment_loss: z.number().min(0, "Must be zero or positive").optional(),
  cf_finance_costs: z.number().min(0, "Must be zero or positive").optional(),
  cf_foreign_exchange_loss: z.number().min(0, "Must be zero or positive").optional(),
  cf_profit_loss_on_assets: z.number().min(0, "Must be zero or positive").optional(),
  cf_trade_receivables_decrease: z.number().min(0, "Must be zero or positive").optional(),
  cf_inventories_decrease: z.number().min(0, "Must be zero or positive").optional(),
  cf_trade_payables_increase: z.number().min(0, "Must be zero or positive").optional(),
  cf_other_payables_increase: z.number().min(0, "Must be zero or positive").optional(),
  cf_current_assets_decrease: z.number().min(0, "Must be zero or positive").optional(),
  cf_current_liabilities_increase: z.number().min(0, "Must be zero or positive").optional(),
  cf_capital_work_purchase: z.number().min(0, "Must be zero or positive").optional(),
  cf_capital_work_sale: z.number().min(0, "Must be zero or positive").optional(),
  cf_investments_purchase: z.number().min(0, "Must be zero or positive").optional(),
  cf_investments_sale: z.number().min(0, "Must be zero or positive").optional(),
  cf_loans_advance_given: z.number().min(0, "Must be zero or positive").optional(),
  cf_loans_advance_received: z.number().min(0, "Must be zero or positive").optional(),
  cf_equity_share_issued: z.number().min(0, "Must be zero or positive").optional(),
  cf_borrowings_taken: z.number().min(0, "Must be zero or positive").optional(),
  cf_borrowings_repaid: z.number().min(0, "Must be zero or positive").optional(),
  cf_dividend_paid: z.number().min(0, "Must be zero or positive").optional(),
  cf_interest_paid: z.number().min(0, "Must be zero or positive").optional(),

  // Notes to Accounts validations
  nt_contingent_liability_1: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_liability_2: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_liability_3: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_liability_4: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_liability_5: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_liability_desc_1: z.string().optional(),
  nt_contingent_liability_desc_2: z.string().optional(),
  nt_contingent_liability_desc_3: z.string().optional(),
  nt_contingent_liability_desc_4: z.string().optional(),
  nt_contingent_liability_desc_5: z.string().optional(),
  nt_capital_commitments_not_authorized: z.number().min(0, "Must be zero or positive").optional(),
  nt_capital_commitments_authorized: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_asset_1: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_asset_2: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_asset_3: z.number().min(0, "Must be zero or positive").optional(),
  nt_contingent_asset_desc_1: z.string().optional(),
  nt_contingent_asset_desc_2: z.string().optional(),
  nt_contingent_asset_desc_3: z.string().optional(),
  nt_related_party_1: z.number().min(0, "Must be zero or positive").optional(),
  nt_related_party_2: z.number().min(0, "Must be zero or positive").optional(),
  nt_related_party_3: z.number().min(0, "Must be zero or positive").optional(),
  nt_related_party_4: z.number().min(0, "Must be zero or positive").optional(),
  nt_related_party_desc_1: z.string().optional(),
  nt_related_party_desc_2: z.string().optional(),
  nt_related_party_desc_3: z.string().optional(),
  nt_related_party_desc_4: z.string().optional(),
  nt_post_events: z.string().optional(),
  nt_restructuring_events: z.string().optional(),
  nt_regulatory_events: z.string().optional(),
  nt_num_employees: z.number().min(0, "Must be zero or positive").optional(),
  nt_employee_benefits: z.string().optional(),
  nt_rd_activities: z.string().optional(),
  nt_csr_activities: z.string().optional(),
  nt_other_disclosures: z.string().optional(),

  // Comprehensive Income Statement validations
  ci_profit_before_interest_depreciation: z.number().min(0, "Must be zero or positive").optional(),
  ci_finance_costs: z.number().min(0, "Must be zero or positive").optional(),
  ci_depreciation_amortization: z.number().min(0, "Must be zero or positive").optional(),
  ci_bad_debts_pan: z.string().optional(),
  ci_bad_debts_total: z.number().min(0, "Must be zero or positive").optional(),
  ci_bad_debts_others: z.number().min(0, "Must be zero or positive").optional(),
  ci_provision_bad_doubtful_debts: z.number().min(0, "Must be zero or positive").optional(),
  ci_provision_current_tax: z.number().min(0, "Must be zero or positive").optional(),
  ci_provision_deferred_tax: z.number().min(0, "Must be zero or positive").optional(),
  ci_transfer_reserves_surplus: z.number().min(0, "Must be zero or positive").optional(),
  ci_proposed_dividend: z.number().min(0, "Must be zero or positive").optional(),
  ci_tax_on_dividend: z.number().min(0, "Must be zero or positive").optional(),
  ci_csr_appropriation: z.number().min(0, "Must be zero or positive").optional(),
  ci_other_appropriation: z.number().min(0, "Must be zero or positive").optional(),
  ci_remeasurement_pension_changes: z.number().min(0, "Must be zero or positive").optional(),
  ci_remeasurement_deferred_benefit: z.number().min(0, "Must be zero or positive").optional(),
  ci_equity_instruments_changes: z.number().min(0, "Must be zero or positive").optional(),
  ci_own_credit_risk_changes: z.number().min(0, "Must be zero or positive").optional(),
  ci_share_other_comprehensive_income: z.number().min(0, "Must be zero or positive").optional(),
  ci_other_not_reclassified_nature: z.number().min(0, "Must be zero or positive").optional(),
  ci_exchange_differences_translation: z.number().min(0, "Must be zero or positive").optional(),
  ci_effective_portion_cash_flow_hedge: z.number().min(0, "Must be zero or positive").optional(),
  ci_gains_losses_hedging_instruments: z.number().min(0, "Must be zero or positive").optional(),
  ci_oci_associates_joint_ventures: z.number().min(0, "Must be zero or positive").optional(),
  ci_other_reclassified_nature: z.number().min(0, "Must be zero or positive").optional(),

  // Schedule CFL: Losses to be carried forward
  cfl_date_2010_11: z.string().optional(),
  cfl_hp_2010_11: z.number().optional(),
  cfl_business_2010_11: z.number().optional(),
  cfl_depreciation_2010_11: z.number().optional(),
  cfl_speculative_2010_11: z.number().optional(),
  cfl_insurance_2010_11: z.number().optional(),
  cfl_insurance_115b_2010_11: z.number().optional(),
  cfl_stcl_2010_11: z.number().optional(),
  cfl_ltcl_2010_11: z.number().optional(),
  cfl_race_horses_2010_11: z.number().optional(),
  
  cfl_date_2011_12: z.string().optional(),
  cfl_hp_2011_12: z.number().optional(),
  cfl_business_2011_12: z.number().optional(),
  cfl_depreciation_2011_12: z.number().optional(),
  cfl_speculative_2011_12: z.number().optional(),
  cfl_insurance_2011_12: z.number().optional(),
  cfl_insurance_115b_2011_12: z.number().optional(),
  cfl_stcl_2011_12: z.number().optional(),
  cfl_ltcl_2011_12: z.number().optional(),
  cfl_race_horses_2011_12: z.number().optional(),

  cfl_date_2012_13: z.string().optional(),
  cfl_hp_2012_13: z.number().optional(),
  cfl_business_2012_13: z.number().optional(),
  cfl_depreciation_2012_13: z.number().optional(),
  cfl_speculative_2012_13: z.number().optional(),
  cfl_insurance_2012_13: z.number().optional(),
  cfl_insurance_115b_2012_13: z.number().optional(),
  cfl_stcl_2012_13: z.number().optional(),
  cfl_ltcl_2012_13: z.number().optional(),
  cfl_race_horses_2012_13: z.number().optional(),

  cfl_date_2013_14: z.string().optional(),
  cfl_hp_2013_14: z.number().optional(),
  cfl_business_2013_14: z.number().optional(),
  cfl_depreciation_2013_14: z.number().optional(),
  cfl_speculative_2013_14: z.number().optional(),
  cfl_insurance_2013_14: z.number().optional(),
  cfl_insurance_115b_2013_14: z.number().optional(),
  cfl_stcl_2013_14: z.number().optional(),
  cfl_ltcl_2013_14: z.number().optional(),
  cfl_race_horses_2013_14: z.number().optional(),

  cfl_date_2014_15: z.string().optional(),
  cfl_hp_2014_15: z.number().optional(),
  cfl_business_2014_15: z.number().optional(),
  cfl_depreciation_2014_15: z.number().optional(),
  cfl_speculative_2014_15: z.number().optional(),
  cfl_insurance_2014_15: z.number().optional(),
  cfl_insurance_115b_2014_15: z.number().optional(),
  cfl_stcl_2014_15: z.number().optional(),
  cfl_ltcl_2014_15: z.number().optional(),
  cfl_race_horses_2014_15: z.number().optional(),

  cfl_date_2015_16: z.string().optional(),
  cfl_hp_2015_16: z.number().optional(),
  cfl_business_2015_16: z.number().optional(),
  cfl_depreciation_2015_16: z.number().optional(),
  cfl_speculative_2015_16: z.number().optional(),
  cfl_insurance_2015_16: z.number().optional(),
  cfl_insurance_115b_2015_16: z.number().optional(),
  cfl_stcl_2015_16: z.number().optional(),
  cfl_ltcl_2015_16: z.number().optional(),
  cfl_race_horses_2015_16: z.number().optional(),

  cfl_date_2016_17: z.string().optional(),
  cfl_hp_2016_17: z.number().optional(),
  cfl_business_2016_17: z.number().optional(),
  cfl_depreciation_2016_17: z.number().optional(),
  cfl_speculative_2016_17: z.number().optional(),
  cfl_insurance_2016_17: z.number().optional(),
  cfl_insurance_115b_2016_17: z.number().optional(),
  cfl_stcl_2016_17: z.number().optional(),
  cfl_ltcl_2016_17: z.number().optional(),
  cfl_race_horses_2016_17: z.number().optional(),

  cfl_date_2017_18: z.string().optional(),
  cfl_hp_2017_18: z.number().optional(),
  cfl_business_2017_18: z.number().optional(),
  cfl_depreciation_2017_18: z.number().optional(),
  cfl_speculative_2017_18: z.number().optional(),
  cfl_insurance_2017_18: z.number().optional(),
  cfl_insurance_115b_2017_18: z.number().optional(),
  cfl_stcl_2017_18: z.number().optional(),
  cfl_ltcl_2017_18: z.number().optional(),
  cfl_race_horses_2017_18: z.number().optional(),

  cfl_date_2018_19: z.string().optional(),
  cfl_hp_2018_19: z.number().optional(),
  cfl_business_2018_19: z.number().optional(),
  cfl_depreciation_2018_19: z.number().optional(),
  cfl_speculative_2018_19: z.number().optional(),
  cfl_insurance_2018_19: z.number().optional(),
  cfl_insurance_115b_2018_19: z.number().optional(),
  cfl_stcl_2018_19: z.number().optional(),
  cfl_ltcl_2018_19: z.number().optional(),
  cfl_race_horses_2018_19: z.number().optional(),

  cfl_date_2019_20: z.string().optional(),
  cfl_hp_2019_20: z.number().optional(),
  cfl_business_2019_20: z.number().optional(),
  cfl_depreciation_2019_20: z.number().optional(),
  cfl_speculative_2019_20: z.number().optional(),
  cfl_insurance_2019_20: z.number().optional(),
  cfl_insurance_115b_2019_20: z.number().optional(),
  cfl_stcl_2019_20: z.number().optional(),
  cfl_ltcl_2019_20: z.number().optional(),
  cfl_race_horses_2019_20: z.number().optional(),

  cfl_date_2020_21: z.string().optional(),
  cfl_hp_2020_21: z.number().optional(),
  cfl_business_2020_21: z.number().optional(),
  cfl_depreciation_2020_21: z.number().optional(),
  cfl_speculative_2020_21: z.number().optional(),
  cfl_insurance_2020_21: z.number().optional(),
  cfl_insurance_115b_2020_21: z.number().optional(),
  cfl_stcl_2020_21: z.number().optional(),
  cfl_ltcl_2020_21: z.number().optional(),
  cfl_race_horses_2020_21: z.number().optional(),

  cfl_date_2021_22: z.string().optional(),
  cfl_hp_2021_22: z.number().optional(),
  cfl_business_2021_22: z.number().optional(),
  cfl_depreciation_2021_22: z.number().optional(),
  cfl_speculative_2021_22: z.number().optional(),
  cfl_insurance_2021_22: z.number().optional(),
  cfl_insurance_115b_2021_22: z.number().optional(),
  cfl_stcl_2021_22: z.number().optional(),
  cfl_ltcl_2021_22: z.number().optional(),
  cfl_race_horses_2021_22: z.number().optional(),

  cfl_date_2022_23: z.string().optional(),
  cfl_hp_2022_23: z.number().optional(),
  cfl_business_2022_23: z.number().optional(),
  cfl_depreciation_2022_23: z.number().optional(),
  cfl_speculative_2022_23: z.number().optional(),
  cfl_insurance_2022_23: z.number().optional(),
  cfl_insurance_115b_2022_23: z.number().optional(),
  cfl_stcl_2022_23: z.number().optional(),
  cfl_ltcl_2022_23: z.number().optional(),
  cfl_race_horses_2022_23: z.number().optional(),

  cfl_date_2023_24: z.string().optional(),
  cfl_hp_2023_24: z.number().optional(),
  cfl_business_2023_24: z.number().optional(),
  cfl_depreciation_2023_24: z.number().optional(),
  cfl_speculative_2023_24: z.number().optional(),
  cfl_insurance_2023_24: z.number().optional(),
  cfl_insurance_115b_2023_24: z.number().optional(),
  cfl_stcl_2023_24: z.number().optional(),
  cfl_ltcl_2023_24: z.number().optional(),
  cfl_race_horses_2023_24: z.number().optional(),

  cfl_date_2024_25: z.string().optional(),
  cfl_hp_2024_25: z.number().optional(),
  cfl_business_2024_25: z.number().optional(),
  cfl_depreciation_2024_25: z.number().optional(),
  cfl_speculative_2024_25: z.number().optional(),
  cfl_insurance_2024_25: z.number().optional(),
  cfl_insurance_115b_2024_25: z.number().optional(),
  cfl_stcl_2024_25: z.number().optional(),
  cfl_ltcl_2024_25: z.number().optional(),
  cfl_race_horses_2024_25: z.number().optional(),

  cfl_total_earlier_years: z.number().optional(),
  cfl_total_hp: z.number().optional(),
  cfl_total_business: z.number().optional(),
  cfl_total_depreciation: z.number().optional(),
  cfl_total_speculative: z.number().optional(),
  cfl_total_insurance: z.number().optional(),
  cfl_total_insurance_115b: z.number().optional(),
  cfl_total_stcl: z.number().optional(),
  cfl_total_ltcl: z.number().optional(),
  cfl_total_race_horses: z.number().optional(),

  // Schedule UD: Unabsorbed Depreciation and Allowance
  ud_assessment_year_ii: z.string().optional(),
  ud_assessment_year_iii: z.string().optional(),
  ud_assessment_year_iv: z.string().optional(),

  ud_dep_bf_current: z.number().optional(),
  ud_dep_adjusted_current: z.number().optional(),
  ud_dep_setoff_current: z.number().optional(),
  ud_dep_balance_current: z.number().optional(),

  ud_allow_bf_current: z.number().optional(),
  ud_allow_setoff_current: z.number().optional(),
  ud_allow_unabsorbed_current: z.number().optional(),
  ud_allow_balance_current: z.number().optional(),

  ud_dep_bf_ii: z.number().optional(),
  ud_dep_adjusted_ii: z.number().optional(),
  ud_dep_setoff_ii: z.number().optional(),
  ud_dep_balance_ii: z.number().optional(),

  ud_dep_bf_iii: z.number().optional(),
  ud_dep_adjusted_iii: z.number().optional(),
  ud_dep_setoff_iii: z.number().optional(),
  ud_dep_balance_iii: z.number().optional(),

  ud_dep_bf_iv: z.number().optional(),
  ud_dep_adjusted_iv: z.number().optional(),
  ud_dep_setoff_iv: z.number().optional(),
  ud_dep_balance_iv: z.number().optional(),

  ud_allow_bf_ii: z.number().optional(),
  ud_allow_setoff_ii: z.number().optional(),
  ud_allow_unabsorbed_ii: z.number().optional(),
  ud_allow_balance_ii: z.number().optional(),

  ud_allow_bf_iii: z.number().optional(),
  ud_allow_setoff_iii: z.number().optional(),
  ud_allow_unabsorbed_iii: z.number().optional(),
  ud_allow_balance_iii: z.number().optional(),

  ud_allow_bf_iv: z.number().optional(),
  ud_allow_setoff_iv: z.number().optional(),
  ud_allow_unabsorbed_iv: z.number().optional(),
  ud_allow_balance_iv: z.number().optional(),

  ud_total_dep_bf: z.number().optional(),
  ud_total_dep_adjusted: z.number().optional(),
  ud_total_dep_setoff: z.number().optional(),
  ud_total_dep_balance: z.number().optional(),

  ud_total_allow_bf: z.number().optional(),
  ud_total_allow_setoff: z.number().optional(),
  ud_total_allow_unabsorbed: z.number().optional(),
  ud_total_allow_balance: z.number().optional(),
}).refine((data) => {
  if (data.gen_name_change === "yes" && !data.gen_old_name) {
    return false;
  }
  return true;
}, {
  message: "Old name is required when there is a name change",
  path: ["gen_old_name"]
}).refine((data) => {
  if (data.gen_representative_assessee === "yes" && !data.gen_representative_name) {
    return false;
  }
  return true;
}, {
  message: "Representative name is required",
  path: ["gen_representative_name"]
}).refine((data) => {
  if (data.gen_audit_accounts_audited === "yes" && !data.gen_audit_report_date) {
    return false;
  }
  return true;
}, {
  message: "Audit report date is required",
  path: ["gen_audit_report_date"]
});
